//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrickBreaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrickBreaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap andesiteBlock {
            get {
                object obj = ResourceManager.GetObject("andesiteBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream audiomass_output {
            get {
                return ResourceManager.GetStream("audiomass_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BigBreak {
            get {
                object obj = ResourceManager.GetObject("BigBreak", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BigmedBreak {
            get {
                object obj = ResourceManager.GetObject("BigmedBreak", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blazeEnemyImage {
            get {
                object obj = ResourceManager.GetObject("blazeEnemyImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream brickCollision {
            get {
                return ResourceManager.GetStream("brickCollision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coalOreBlock {
            get {
                object obj = ResourceManager.GetObject("coalOreBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copperOreBlock {
            get {
                object obj = ResourceManager.GetObject("copperOreBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] deathMusic {
            get {
                object obj = ResourceManager.GetObject("deathMusic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deathScreen {
            get {
                object obj = ResourceManager.GetObject("deathScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deepslateBlock {
            get {
                object obj = ResourceManager.GetObject("deepslateBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deepslateBrickBlock {
            get {
                object obj = ResourceManager.GetObject("deepslateBrickBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deepslateCoalOreBlock {
            get {
                object obj = ResourceManager.GetObject("deepslateCoalOreBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deepslateDiamondOreBlock {
            get {
                object obj = ResourceManager.GetObject("deepslateDiamondOreBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deepslateEmeraldOreBlock {
            get {
                object obj = ResourceManager.GetObject("deepslateEmeraldOreBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deepslateGoldOreBlock {
            get {
                object obj = ResourceManager.GetObject("deepslateGoldOreBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deepslateIronOreBlock {
            get {
                object obj = ResourceManager.GetObject("deepslateIronOreBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deepslateLapisOreBlock {
            get {
                object obj = ResourceManager.GetObject("deepslateLapisOreBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deepslateRedstoneOreBlock {
            get {
                object obj = ResourceManager.GetObject("deepslateRedstoneOreBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dirtBackground2 {
            get {
                object obj = ResourceManager.GetObject("dirtBackground2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dirtBlock {
            get {
                object obj = ResourceManager.GetObject("dirtBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap emptyHeartImage {
            get {
                object obj = ResourceManager.GetObject("emptyHeartImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ghastPlayer {
            get {
                object obj = ResourceManager.GetObject("ghastPlayer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap goldenHeartImage {
            get {
                object obj = ResourceManager.GetObject("goldenHeartImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap graniteBlock {
            get {
                object obj = ResourceManager.GetObject("graniteBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grassBlock {
            get {
                object obj = ResourceManager.GetObject("grassBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream impact2 {
            get {
                return ResourceManager.GetStream("impact2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ironOreBlock {
            get {
                object obj = ResourceManager.GetObject("ironOreBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap leadboardButton__1_ {
            get {
                object obj = ResourceManager.GetObject("leadboardButton__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap leaderboardBackground {
            get {
                object obj = ResourceManager.GetObject("leaderboardBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] leaderboardMusic {
            get {
                object obj = ResourceManager.GetObject("leaderboardMusic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Level&gt;
        ///	&lt;Block&gt;
        ///		&lt;x&gt;916&lt;/x&gt;
        ///		&lt;y&gt;538&lt;/y&gt;
        ///		&lt;type&gt;grass&lt;/type&gt;
        ///	&lt;/Block&gt;
        ///	&lt;Block&gt;
        ///		&lt;x&gt;664&lt;/x&gt;
        ///		&lt;y&gt;538&lt;/y&gt;
        ///		&lt;type&gt;grass&lt;/type&gt;
        ///	&lt;/Block&gt;
        ///	&lt;Block&gt;
        ///		&lt;x&gt;538&lt;/x&gt;
        ///		&lt;y&gt;538&lt;/y&gt;
        ///		&lt;type&gt;grass&lt;/type&gt;
        ///	&lt;/Block&gt;
        ///	&lt;Block&gt;
        ///		&lt;x&gt;790&lt;/x&gt;
        ///		&lt;y&gt;538&lt;/y&gt;
        ///		&lt;type&gt;grass&lt;/type&gt;
        ///	&lt;/Block&gt;
        ///	&lt;Block&gt;
        ///		&lt;x&gt;412&lt;/x&gt;
        ///		&lt;y&gt;538&lt;/y&gt;
        ///		&lt;type&gt;grass&lt;/type&gt;
        ///	&lt;/Block&gt;
        ///	&lt;Block&gt;
        ///		&lt;x&gt;286&lt;/x&gt;
        ///		&lt;y&gt;538&lt;/y&gt;
        ///		&lt;type&gt;grass&lt;/type&gt;
        ///	&lt;/Block&gt;
        ///	&lt;Block&gt;
        ///		&lt;x&gt;160&lt;/x&gt;
        ///		&lt;y&gt;538&lt;/y&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level0 {
            get {
                return ResourceManager.GetString("level0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap level0Background {
            get {
                object obj = ResourceManager.GetObject("level0Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] level0Music {
            get {
                object obj = ResourceManager.GetObject("level0Music", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Level&gt;
        ///	&lt;Block&gt;
        ///		&lt;x&gt;916&lt;/x&gt;
        ///		&lt;y&gt;629&lt;/y&gt;
        ///		&lt;type&gt;stone&lt;/type&gt;
        ///	&lt;/Block&gt;
        ///	&lt;Block&gt;
        ///		&lt;x&gt;664&lt;/x&gt;
        ///		&lt;y&gt;629&lt;/y&gt;
        ///		&lt;type&gt;granite&lt;/type&gt;
        ///	&lt;/Block&gt;
        ///	&lt;Block&gt;
        ///		&lt;x&gt;538&lt;/x&gt;
        ///		&lt;y&gt;629&lt;/y&gt;
        ///		&lt;type&gt;granite&lt;/type&gt;
        ///	&lt;/Block&gt;
        ///	&lt;Block&gt;
        ///		&lt;x&gt;790&lt;/x&gt;
        ///		&lt;y&gt;629&lt;/y&gt;
        ///		&lt;type&gt;granite&lt;/type&gt;
        ///	&lt;/Block&gt;
        ///	&lt;Block&gt;
        ///		&lt;x&gt;412&lt;/x&gt;
        ///		&lt;y&gt;629&lt;/y&gt;
        ///		&lt;type&gt;stone&lt;/type&gt;
        ///	&lt;/Block&gt;
        ///	&lt;Block&gt;
        ///		&lt;x&gt;286&lt;/x&gt;
        ///		&lt;y&gt;629&lt;/y&gt;
        ///		&lt;type&gt;stone&lt;/type&gt;
        ///	&lt;/Block&gt;
        ///	&lt;Block&gt;
        ///		&lt;x&gt;160&lt;/x&gt;
        ///		&lt;y&gt;62 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level1 {
            get {
                return ResourceManager.GetString("level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap level1Background {
            get {
                object obj = ResourceManager.GetObject("level1Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] level1Music {
            get {
                object obj = ResourceManager.GetObject("level1Music", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;Level&gt;&lt;Block&gt;&lt;x&gt;916&lt;/x&gt;&lt;y&gt;445&lt;/y&gt;&lt;type&gt;stone&lt;/type&gt;&lt;/Block&gt;&lt;Block&gt;&lt;x&gt;664&lt;/x&gt;&lt;y&gt;445&lt;/y&gt;&lt;type&gt;dirt&lt;/type&gt;&lt;/Block&gt;&lt;Block&gt;&lt;x&gt;538&lt;/x&gt;&lt;y&gt;445&lt;/y&gt;&lt;type&gt;andesite&lt;/type&gt;&lt;/Block&gt;&lt;Block&gt;&lt;x&gt;790&lt;/x&gt;&lt;y&gt;445&lt;/y&gt;&lt;type&gt;zombie&lt;/type&gt;&lt;/Block&gt;&lt;Block&gt;&lt;x&gt;412&lt;/x&gt;&lt;y&gt;445&lt;/y&gt;&lt;type&gt;andesite&lt;/type&gt;&lt;/Block&gt;&lt;Block&gt;&lt;x&gt;286&lt;/x&gt;&lt;y&gt;445&lt;/y&gt;&lt;type&gt;stone&lt;/type&gt;&lt;/Block&gt;&lt;Block&gt;&lt;x&gt;160&lt;/x&gt;&lt;y&gt;445&lt;/y&gt;&lt;type&gt;dirt&lt;/type&gt;&lt;/Block&gt;&lt;Block&gt;&lt;x&gt;34&lt;/x&gt;&lt;y&gt;445&lt;/y&gt;&lt;type&gt;stone&lt;/type&gt;&lt;/Block&gt;&lt;Block&gt;&lt;x&gt;916&lt;/x&gt;&lt;y&gt;629&lt;/y&gt;&lt;type&gt;stone&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level2 {
            get {
                return ResourceManager.GetString("level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap level2Background {
            get {
                object obj = ResourceManager.GetObject("level2Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] level2Music {
            get {
                object obj = ResourceManager.GetObject("level2Music", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;Level&gt;&lt;Block&gt;&lt;x&gt;916&lt;/x&gt;&lt;y&gt;445&lt;/y&gt;&lt;type&gt;deepslate&lt;/type&gt;&lt;/Block&gt;&lt;Block&gt;&lt;x&gt;664&lt;/x&gt;&lt;y&gt;445&lt;/y&gt;&lt;type&gt;deepslate&lt;/type&gt;&lt;/Block&gt;&lt;Block&gt;&lt;x&gt;538&lt;/x&gt;&lt;y&gt;445&lt;/y&gt;&lt;type&gt;deepslateTile&lt;/type&gt;&lt;/Block&gt;&lt;Block&gt;&lt;x&gt;790&lt;/x&gt;&lt;y&gt;445&lt;/y&gt;&lt;type&gt;deepslate&lt;/type&gt;&lt;/Block&gt;&lt;Block&gt;&lt;x&gt;412&lt;/x&gt;&lt;y&gt;445&lt;/y&gt;&lt;type&gt;deepslate&lt;/type&gt;&lt;/Block&gt;&lt;Block&gt;&lt;x&gt;286&lt;/x&gt;&lt;y&gt;445&lt;/y&gt;&lt;type&gt;deepslate&lt;/type&gt;&lt;/Block&gt;&lt;Block&gt;&lt;x&gt;160&lt;/x&gt;&lt;y&gt;445&lt;/y&gt;&lt;type&gt;deepslateTile&lt;/type&gt;&lt;/Block&gt;&lt;Block&gt;&lt;x&gt;34&lt;/x&gt;&lt;y&gt;445&lt;/y&gt;&lt;type&gt;deepslate&lt;/type&gt;&lt;/Block&gt;&lt;Blo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level3 {
            get {
                return ResourceManager.GetString("level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap level3Background {
            get {
                object obj = ResourceManager.GetObject("level3Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] level3Music {
            get {
                object obj = ResourceManager.GetObject("level3Music", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Level&gt;
        ///	&lt;Block&gt;
        ///		&lt;x&gt;916&lt;/x&gt;
        ///		&lt;y&gt;445&lt;/y&gt;
        ///		&lt;type&gt;netherack&lt;/type&gt;
        ///	&lt;/Block&gt;
        ///	&lt;Block&gt;
        ///		&lt;x&gt;664&lt;/x&gt;
        ///		&lt;y&gt;445&lt;/y&gt;
        ///		&lt;type&gt;blaze&lt;/type&gt;
        ///	&lt;/Block&gt;
        ///	&lt;Block&gt;
        ///		&lt;x&gt;538&lt;/x&gt;
        ///		&lt;y&gt;445&lt;/y&gt;
        ///		&lt;type&gt;netherack&lt;/type&gt;
        ///	&lt;/Block&gt;
        ///	&lt;Block&gt;
        ///		&lt;x&gt;790&lt;/x&gt;
        ///		&lt;y&gt;445&lt;/y&gt;
        ///		&lt;type&gt;magma&lt;/type&gt;
        ///	&lt;/Block&gt;
        ///	&lt;Block&gt;
        ///		&lt;x&gt;412&lt;/x&gt;
        ///		&lt;y&gt;445&lt;/y&gt;
        ///		&lt;type&gt;netherack&lt;/type&gt;
        ///	&lt;/Block&gt;
        ///	&lt;Block&gt;
        ///		&lt;x&gt;286&lt;/x&gt;
        ///		&lt;y&gt;445&lt;/y&gt;
        ///		&lt;type&gt;blaze&lt;/type&gt;
        ///	&lt;/Block&gt;
        ///	&lt;Block&gt;
        ///		&lt;x&gt;160&lt;/x&gt;
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level4 {
            get {
                return ResourceManager.GetString("level4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap level4Background {
            get {
                object obj = ResourceManager.GetObject("level4Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] level4Music {
            get {
                object obj = ResourceManager.GetObject("level4Music", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap magmaBlock {
            get {
                object obj = ResourceManager.GetObject("magmaBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] mainMenuMusic {
            get {
                object obj = ResourceManager.GetObject("mainMenuMusic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minecraftHeartImage {
            get {
                object obj = ResourceManager.GetObject("minecraftHeartImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minecraftMainMenuScreen {
            get {
                object obj = ResourceManager.GetObject("minecraftMainMenuScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap netherGoldBlock {
            get {
                object obj = ResourceManager.GetObject("netherGoldBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap netheriteOreBlock {
            get {
                object obj = ResourceManager.GetObject("netheriteOreBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap netherraackBlock {
            get {
                object obj = ResourceManager.GetObject("netherraackBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap obsidianBlock {
            get {
                object obj = ResourceManager.GetObject("obsidianBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream paddleHit {
            get {
                return ResourceManager.GetStream("paddleHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Players&gt;
        ///  &lt;Player&gt;
        ///    &lt;Username&gt;a&lt;/Username&gt;
        ///    &lt;Password&gt;a&lt;/Password&gt;
        ///    &lt;Score&gt;0&lt;/Score&gt;
        ///  &lt;/Player&gt;
        ///&lt;/Players&gt;.
        /// </summary>
        internal static string playerData {
            get {
                return ResourceManager.GetString("playerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap quartzOreBlock {
            get {
                object obj = ResourceManager.GetObject("quartzOreBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap skeletonEnemyImage {
            get {
                object obj = ResourceManager.GetObject("skeletonEnemyImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SmallBreak {
            get {
                object obj = ResourceManager.GetObject("SmallBreak", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SmallmedBreak {
            get {
                object obj = ResourceManager.GetObject("SmallmedBreak", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stoneBlock {
            get {
                object obj = ResourceManager.GetObject("stoneBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] winMusic {
            get {
                object obj = ResourceManager.GetObject("winMusic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap winScreens {
            get {
                object obj = ResourceManager.GetObject("winScreens", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream winSound {
            get {
                return ResourceManager.GetStream("winSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zombieEnemyImage {
            get {
                object obj = ResourceManager.GetObject("zombieEnemyImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
